BASE_URL = 'https://2ch.hk'  # 2ch url, if .hk didn't work use other, e.g. .pm
BOARDS = ['b', 'vg']  # Список борд на которых искать
PATTERNS = ['webm', 'шебм', 'цуиь', 'fap', 'фап', 'афз', 'afg', ]  # Required substrings in OP post
ALLOWED_EXT = ['webm', 'mp4', ]
ANTI_PATTERNS = ['black', 'рулет', ]  # Didn't required substrings in OP post
MIN_REPLIES = 3  # Minimum replies to match post
MAX_QUEUE_SIZE = 30  # Maximum download queues
CHUNK_SIZE = 1024 * 1024  # TODO: Подобрать подходящий размер чанка. Сейчас 1 МБ.
TIMEOUT = 100  # You can increase this value if you have TimeoutError.
